### ISSUE TITLE
Where to download txt files of extract_audio.py

### ISSUE THREAD

**Issue by tubinwei** [astorfi/3D-convolutional-speaker-recognition-pytorch#6]
hello.I went to the official website and downloaded audio dataset that  contains five files A,B,C,D, and test,etc.And the files don't contains any txt files.Someone can help me, please

**Comment by astorfi** [comment]
In the dataset, the .txt file was there to demonstrate the path to the associated files. I am not quite sure how the new version of the dataset is.

**Comment by tubinwei** [comment]
thank you for your much.I see what you mean.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Amirsina Torfi"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月17日(星期二) 凌晨4:53
收件人:&nbsp;"astorfi/3D-convolutional-speaker-recognition-pytorch"<3D-convolutional-speaker-recognition-pytorch@noreply.github.com&gt;;
抄送:&nbsp;"斌炜"<1083974092@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [astorfi/3D-convolutional-speaker-recognition-pytorch] Where to download txt files of extract_audio.py (#6)




In the dataset, the .txt file was there to demonstrate the path to the associated files. I am not quite sure how the new version of the dataset is.

**Comment by tubinwei** [comment]
Hello ，I am sorry to bother you again, I think this is a good implementation, so I spent a few days learning and running the code. &nbsp;But my results seem a bit low,the AUC of the result &nbsp;is 0.60.Could you tell me the results of your experience?
I have a question that you used the “PRELU” activation function on development phase,but you used the RELU activation function on enrollment and evaluation phase .&nbsp;Should I replace the original "prelu" function with the "relu" function during the development phase?


I look forward to hearing from you.


发自我的iPhone


------------------ Original ------------------

**Comment by stanic1717** [comment]
> thank you for your much.I see what you mean.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Amirsina Torfi"<notifications@github.com&gt;; 发送时间:&nbsp;2019年9月17日(星期二) 凌晨4:53 收件人:&nbsp;"astorfi/3D-convolutional-speaker-recognition-pytorch"<3D-convolutional-speaker-recognition-pytorch@noreply.github.com&gt;; 抄送:&nbsp;"斌炜"<1083974092@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;; 主题:&nbsp;Re: [astorfi/3D-convolutional-speaker-recognition-pytorch] Where to download txt files of extract_audio.py (#6) In the dataset, the .txt file was there to demonstrate the path to the associated files. I am not quite sure how the new version of the dataset is. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.

Hello sir, I also encountered the same problem about .txt files, I really want to know how to solved it.Could you help me with it,please?

**Comment by stanic1717** [comment]
@tubinwei Hello sir, I also encountered the same problem about .txt files. I really want to know how to solved it. Could you help me,please?

**Comment by astorfi** [comment]
> Hello ，I am sorry to bother you again, I think this is a good implementation, so I spent a few days learning and running the code. &nbsp;But my results seem a bit low,the AUC of the result &nbsp;is 0.60.Could you tell me the results of your experience? I have a question that you used the “PRELU” activation function on development phase,but you used the RELU activation function on enrollment and evaluation phase .&nbsp;Should I replace the original "prelu" function with the "relu" function during the development phase? I look forward to hearing from you. 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: Amirsina Torfi <notifications@github.com&gt; Date: Tue,Sep 17,2019 4:53 AM To: astorfi/3D-convolutional-speaker-recognition-pytorch <3D-convolutional-speaker-recognition-pytorch@noreply.github.com&gt; Cc: tubinwei <1083974092@qq.com&gt;, State change <state_change@noreply.github.com&gt; Subject: Re: [astorfi/3D-convolutional-speaker-recognition-pytorch] Where to download txt files of extract_audio.py (#6) In the dataset, the .txt file was there to demonstrate the path to the associated files. I am not quite sure how the new version of the dataset is. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.
You can replace all activations with one specific type such as relu or prelu.

**Comment by astorfi** [comment]
> @tubinwei Hello sir, I also encountered the same problem about .txt files. I really want to know how to solved it. Could you help me,please?

The text file belongs to the input pipeline. You can create your own input pipeline.
